// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXHeV5FZoYP7T6HeEC8pvRmq4yKidOCa0',
    appId: '1:311070955861:web:23377e0eb211b1801a77dc',
    messagingSenderId: '311070955861',
    projectId: 'educative-todo-app',
    authDomain: 'educative-todo-app.firebaseapp.com',
    storageBucket: 'educative-todo-app.appspot.com',
    measurementId: 'G-XQV1BDPMTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qlXVGIokobY08XLuQDWhTzPAEUmaut4',
    appId: '1:311070955861:android:484d3399e8594cec1a77dc',
    messagingSenderId: '311070955861',
    projectId: 'educative-todo-app',
    storageBucket: 'educative-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmJ9vF1kIDea0WAqh554xWOBETRWXsKc',
    appId: '1:311070955861:ios:b2438493d363d5021a77dc',
    messagingSenderId: '311070955861',
    projectId: 'educative-todo-app',
    storageBucket: 'educative-todo-app.appspot.com',
    iosClientId: '311070955861-28eiv351bjkri1nobrqaq6lkbisn5i6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxTodoExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmJ9vF1kIDea0WAqh554xWOBETRWXsKc',
    appId: '1:311070955861:ios:fd1456fecc21a23a1a77dc',
    messagingSenderId: '311070955861',
    projectId: 'educative-todo-app',
    storageBucket: 'educative-todo-app.appspot.com',
    iosClientId: '311070955861-7rqtdho9trv1l8dr66c2ph7kcq28oivn.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxTodoExample.RunnerTests',
  );
}
